### ISSUE TITLE
Arsenic Bite perk 1 and perk 2 pools mixed up

### ISSUE THREAD

**Issue by rafigalb** [scspriggy/Spriggys-Wishlist#1]
For example Archer's Tempo and Dragonfly should not be on the same perk pool (or "section/column"). Makes it so when a bow has both of those it only highlights 1 of them. Its not a big deal because I don't really like or use the bow, but I noticed the discrepancy and thought I would share.

**Comment by scspriggy** [comment]
Have you checked the perk pool?  It's wonky for arsenic bite and can drop rampage and archer's tempo on both perk 1 and perk 2: https://destinytracker.com/destiny-2/db/items/720351795-arsenic-bite-4b

**Comment by rafigalb** [comment]
I checked it on light.gg but I see now that archers tempo can drop on perk 1 if its the curated roll, that's why it seems wonky. I've seen that happen with other weapons as well but didn't notice it on this one.

**Comment by rafigalb** [comment]
I wonder if there's a workaround, because the way the wishlist is written it behaves oddly if its not the curated roll.

Here's an example:
![image](https://user-images.githubusercontent.com/46434351/69981896-3ebdd400-1501-11ea-844a-bf8a3a00de1b.png)

Dragonfly should be highlighted, no?

**Comment by scspriggy** [comment]
Not sure what you mean by highlighted, but I sorted all the rolls to ensure the highest roll is selected for an item.  The thumbs up are community ratings, and I never list perk1 or perk2 in notes since they usually aren't changeable like the barrel/mag.

**Comment by rafigalb** [comment]
The thumbs up marks the perks that the wishlist points to. 

I just loaded a test wishlist with only:
```
//Arsenic Bite-4b
dimwishlist:item=720351795&perks=2801223209,16392701,2848615171,201365942
```

And those are the perks that got highlighted with the thumbs up:
![image](https://user-images.githubusercontent.com/46434351/69986862-3ae37f00-150c-11ea-9406-11044f0df7df.png)

**Comment by scspriggy** [comment]
Wow, that's a huge change they snuck in there, not even in their update notes.  Anyways, try the new wishlist I uploaded 2 hours ago, hoping sorting resolved that issue.

**Comment by rafigalb** [comment]
It didn't resolve the issue with the Arsenic Bite (still appears to be ignoring the dragonfly perk), but it did resolve another issue with an Erentil that was showing a low PVE score instead of the high PVP score. Very nice!

**Comment by scspriggy** [comment]
Odd, so it looks like it's matching properly to my list (1.4 for tactile string + 3 for dragonfly + 3 for archer's temp), hence the 7.4 rating, but for some reason DIM isn't giving the thumbs up on dragonfly.  Not sure, but this seems like more of a DIM issue. Would you agree?

**Comment by rafigalb** [comment]
Oh! I think I figured it out! Looks like you are using Dragonfly ID 3865257976 which is unique for Oxygen SR3. Dragonfly ID 2848615171 is the one used in random rolls.

**Comment by scspriggy** [comment]
Wow, nice catch!  Wanna check it with the new upload?

**Comment by rafigalb** [comment]
Okay I checked and Dragonfly was still not being flagged. Did some more testing and edited the note on each of the 7.4 ratings for this weapon in your list and found that DIM is actually matching a prior entry before the one that includes Dragonfly.

For example, I created a new wishlist with just:
```
dimwishlist:item=720351795&perks=1196733167,201365942,201365942#notes:Test 1
dimwishlist:item=720351795&perks=1196733167,201365942,3425386926#notes:Test 2
dimwishlist:item=720351795&perks=1196733167,3425386926,201365942#notes:Test 3
dimwishlist:item=720351795&perks=1196733167,3425386926,3425386926#notes:Test 4
dimwishlist:item=720351795&perks=1196733167,2848615171,201365942#notes:Test 5
dimwishlist:item=720351795&perks=1196733167,2848615171,3425386926#notes:Test 6
```

My specific roll is Test 3 but because 2 perks match with Test 1, that is the one DIM is displaying.

Does it make any sense? Lol I wouldn't blame you if it doesn't, I'mm not doing a very good job of explaining my thoughts.

Anyways I'm thinking it IS a DIM issue, not your list. :)

**Comment by rafigalb** [comment]
Hmm, scratch that. I messed up my Test list.

**Comment by scspriggy** [comment]
I'm pretty sure it does work that way though, it will take the first match and ignore any further matches.

**Comment by rafigalb** [comment]
Yeah seems that's what is happening. Its matching 2 perks when it could match 3, 2 lines below it. Not sure if you can do anything with your lists to work around that limitation.

**Comment by rafigalb** [comment]
Otherwise the list is looking beautiful!

**Comment by scspriggy** [comment]
I figured sorting it by max value would do that, but looks like it's not?

**Comment by rafigalb** [comment]
I think that it does help tremendously to sort by value, but in this case its the same value, so it just picked the top one. Doesn't seem like a problem to me since even if it doesn't mark the dragonfly perk it still assigns the correct value. Just an UI inconvenience, still very functional and helpful.

**Comment by rafigalb** [comment]
My main worry was that there was something else going on, but now that I understand it better I'm super happy with your list.
